### ISSUE TITLE
token passed to request as parameter

### ISSUE THREAD

**Issue by f-liva** [gabrielsomoza/oauth2-middleware#7]
Hello,

First of all your package is awesome and is a real game changer working on Guzzle.

One question, there is a way to pass the retrieved token to requests as a GET parameter instead as the Authorization header?

**Comment by gsomoza** [comment]
There's currently no way of doing that directly through this library. What you could do is create your own implementation of [`Bearer`](https://github.com/gsomoza/oauth2-middleware/blob/master/src/Bearer.php) that uses a GET parameter instead of the authorization header.

Having said that, if you could change the authentication server to support the header instead of a GET paramater, that would probably be better in many ways - including the fact that GET URLs are usually logged by several servers, which could expose the Access Token to anyone who can read those logs..

**Comment by gsomoza** [comment]
(FYI closing the ticket, but we can keep talking :) )

**Comment by f-liva** [comment]
Yes I understand, however I'm using some pseudo-REST providers that want token passed as GET parameter.

I'll do a implementation and I'll PR to this repo for those need it.

**Comment by gsomoza** [comment]
Maybe we should promote the `Bearer` class to a more generic abstraction, such as `TokenAuthenticationMiddleware`, and delegate the responsibility of actually updating the request to other classes based on the token's actual "type": we'd have the "bearer" type (like we do now) and then you'd add your own implementation for a new type (e.g. "QueryParameter").

Just an idea, but I think it would provide a more flexible implementation. Here's a draft: https://gist.github.com/gsomoza/41a32263b0cad61ecab2d959b79bc3d5#file-tokenauthenticationmiddleware-php

**Comment by f-liva** [comment]
That would be a great enhancement that will enable all possible methods of implementation.

Do you release that in a release so I could just benefit of the interface?

**Comment by gsomoza** [comment]
It will be quite a bit of work, so I'm not sure I'll be able to do it short-term - but if you do have the time feel free to work on it.

**Comment by f-liva** [comment]
Ok, I'll do really soon

**Comment by gsomoza** [comment]
FYI I was able to squeeze in a few hours of work and here's the result (WIP): https://github.com/gsomoza/oauth2-middleware/tree/feature/refactor

See `src/TokenService/AbstractTokenService.php` - you should be able to extend that in order to create your own version of `Bearer` that uses the query string instead of the headers.

**Comment by gsomoza** [comment]
Update: I'm about to release that branch with PR #10 . Feedback is welcome.
